language: python


python:
  - "3.6.3"


services:
  - postgresql


cache: pip


env:
  global:
    - APP_SETTINGS="project.config.TestingConfig"
    - DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test
    - SECRET_KEY=secret
    - FLASK_APP=ezasdf_users.py


install:
  - pip install -r requirements.txt


before_script:
  - psql -c 'create database users_test;' -U postgres
  - flask recreate_db


script:
  - flask test --cov