language: python


python:
  - "3.6.2"


services:
  - postgresql


cache: pip


env:
  global:
    - APP_SETTINGS="project.config.TestingConfig"
    - DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test
    - SECRET_KEY=secret


install:
  - pip install -r requirements.txt


before_script:
  - psql -c 'create database users_test;' -U postgres
  - python manage.py recreate_db


script:
  - python manage.py cov