language: python
sudo: required

python:
  - "3.6.2"

services:
  - docker
  - postgresql

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.17.1
    - APP_SETTINGS="project.config.TestingConfig"
    - DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database users_test;' -U postgres
  - python manage.py recreate_db
  - docker-compose up -d --build

script:
  - python manage.py test
  - docker-compose run users-service python manage.py test

after_script:
  - docker-compose down